import { ZERO_ADDRESS } from "./constants";
import { type RoadType } from "./types";

const playerAddress = ZERO_ADDRESS;
const direction = "down";

export const allPossibleRoads: RoadType[] = [
  { id: "0003", playerAddress, direction: "left" },
  { id: "0004", playerAddress, direction: "right" },
  { id: "0104", playerAddress, direction: "left" },
  { id: "0105", playerAddress, direction: "right" },
  { id: "0205", playerAddress, direction: "left" },
  { id: "0206", playerAddress, direction: "right" },
  { id: "0307", playerAddress, direction },
  { id: "0408", playerAddress, direction },
  { id: "0509", playerAddress, direction },
  { id: "060a", playerAddress, direction },
  { id: "070b", playerAddress, direction: "left" },
  { id: "070c", playerAddress, direction: "right" },
  { id: "080c", playerAddress, direction: "left" },
  { id: "080d", playerAddress, direction: "right" },
  { id: "090d", playerAddress, direction: "left" },
  { id: "090e", playerAddress, direction: "right" },
  { id: "0a0e", playerAddress, direction: "left" },
  { id: "0a0f", playerAddress, direction: "right" },
  { id: "0b10", playerAddress, direction },
  { id: "0c11", playerAddress, direction },
  { id: "0d12", playerAddress, direction },
  { id: "0e13", playerAddress, direction },
  { id: "0f14", playerAddress, direction },
  { id: "1015", playerAddress, direction: "left" },
  { id: "1016", playerAddress, direction: "right" },
  { id: "1116", playerAddress, direction: "left" },
  { id: "1117", playerAddress, direction: "right" },
  { id: "1217", playerAddress, direction: "left" },
  { id: "1218", playerAddress, direction: "right" },
  { id: "1318", playerAddress, direction: "left" },
  { id: "1319", playerAddress, direction: "right" },
  { id: "1419", playerAddress, direction: "left" },
  { id: "141a", playerAddress, direction: "right" },
  { id: "151b", playerAddress, direction },
  { id: "161c", playerAddress, direction },
  { id: "171d", playerAddress, direction },
  { id: "181e", playerAddress, direction },
  { id: "191f", playerAddress, direction },
  { id: "1a20", playerAddress, direction },
  { id: "1b21", playerAddress, direction: "right" },
  { id: "1c21", playerAddress, direction: "left" },
  { id: "1c22", playerAddress, direction: "right" },
  { id: "1d22", playerAddress, direction: "left" },
  { id: "1d23", playerAddress, direction: "right" },
  { id: "1e23", playerAddress, direction: "left" },
  { id: "1e24", playerAddress, direction: "right" },
  { id: "1f24", playerAddress, direction: "left" },
  { id: "1f25", playerAddress, direction: "right" },
  { id: "2025", playerAddress, direction: "left" },
  { id: "2126", playerAddress, direction },
  { id: "2227", playerAddress, direction },
  { id: "2328", playerAddress, direction },
  { id: "2429", playerAddress, direction },
  { id: "252a", playerAddress, direction },
  { id: "262b", playerAddress, direction: "right" },
  { id: "272b", playerAddress, direction: "left" },
  { id: "272c", playerAddress, direction: "right" },
  { id: "282c", playerAddress, direction: "left" },
  { id: "282d", playerAddress, direction: "right" },
  { id: "292d", playerAddress, direction: "left" },
  { id: "292e", playerAddress, direction: "right" },
  { id: "2a2e", playerAddress, direction: "left" },
  { id: "2b2f", playerAddress, direction },
  { id: "2c30", playerAddress, direction },
  { id: "2d31", playerAddress, direction },
  { id: "2e32", playerAddress, direction },
  { id: "2f33", playerAddress, direction: "right" },
  { id: "3033", playerAddress, direction: "left" },
  { id: "3034", playerAddress, direction: "right" },
  { id: "3134", playerAddress, direction: "left" },
  { id: "3135", playerAddress, direction: "right" },
  { id: "3235", playerAddress, direction: "left" },
];
